export const USERTESTDATA_LOADING = "USERTESTDATA_LOADING";
export const USERTESTDATA_SUCCESS = "USERTESTDATA_SUCCESS";
export const USERTESTDATA_ERROR = "USERTESTDATA_ERROR";
// export const USERTESTDATA_LOADING = ""